version: "3"

tasks:
  generate:
    desc: Run all code generators
    deps: [gen]

  fmt:
    cmds:
      - go tool gofumpt -l -w .

  gen:
    cmds:
      - go generate ./...
      - task: fmt

  docker:
    cmds:
      - docker build -t htqrcode .
