// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package dbmodels

import (
	"context"
	"database/sql"
)

const countLiveLinksByUser = `-- name: CountLiveLinksByUser :one
SELECT count(*)
FROM shorten_url.links
WHERE user_id = $1 AND deactivated_at IS NULL AND expires_at > $2
`

type CountLiveLinksByUserParams struct {
	UserID    string
	ExpiresAt int64
}

func (q *Queries) CountLiveLinksByUser(ctx context.Context, arg CountLiveLinksByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveLinksByUser, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldLinks = `-- name: DeleteOldLinks :exec
DELETE FROM shorten_url.links
WHERE (deactivated_at IS NOT NULL AND deactivated_at < $1)
   OR expires_at < $1
`

func (q *Queries) DeleteOldLinks(ctx context.Context, before sql.NullInt64) error {
	_, err := q.db.Exec(ctx, deleteOldLinks, before)
	return err
}

const getActiveLinkByCode = `-- name: GetActiveLinkByCode :one
SELECT id, user_id, long_url, short_code, idempotency_key, created_at, expires_at, deactivated_at
FROM shorten_url.links
WHERE short_code = $1 AND deactivated_at IS NULL AND expires_at > $2
`

type GetActiveLinkByCodeParams struct {
	ShortCode string
	ExpiresAt int64
}

func (q *Queries) GetActiveLinkByCode(ctx context.Context, arg GetActiveLinkByCodeParams) (ShortenUrlLink, error) {
	row := q.db.QueryRow(ctx, getActiveLinkByCode, arg.ShortCode, arg.ExpiresAt)
	var i ShortenUrlLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LongUrl,
		&i.ShortCode,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getLinkByUserAndIdempotency = `-- name: GetLinkByUserAndIdempotency :one
SELECT id, user_id, long_url, short_code, idempotency_key, created_at, expires_at, deactivated_at
FROM shorten_url.links
WHERE user_id = $1 AND idempotency_key = $2
`

type GetLinkByUserAndIdempotencyParams struct {
	UserID         string
	IdempotencyKey string
}

func (q *Queries) GetLinkByUserAndIdempotency(ctx context.Context, arg GetLinkByUserAndIdempotencyParams) (ShortenUrlLink, error) {
	row := q.db.QueryRow(ctx, getLinkByUserAndIdempotency, arg.UserID, arg.IdempotencyKey)
	var i ShortenUrlLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LongUrl,
		&i.ShortCode,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const insertLink = `-- name: InsertLink :one
INSERT INTO shorten_url.links (
  id, user_id, long_url, short_code, idempotency_key, created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
RETURNING id, user_id, long_url, short_code, idempotency_key, created_at, expires_at, deactivated_at
`

type InsertLinkParams struct {
	ID             string
	UserID         string
	LongUrl        string
	ShortCode      string
	IdempotencyKey string
	CreatedAt      int64
	ExpiresAt      int64
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) (ShortenUrlLink, error) {
	row := q.db.QueryRow(ctx, insertLink,
		arg.ID,
		arg.UserID,
		arg.LongUrl,
		arg.ShortCode,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ShortenUrlLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LongUrl,
		&i.ShortCode,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DeactivatedAt,
	)
	return i, err
}
