// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package dbmodels

import (
	"context"
	"database/sql"
)

const claimMetadata = `-- name: ClaimMetadata :one
UPDATE shorten_url.metadata
SET attempts = attempts + 1, next_attempt_at = $1
WHERE link_id = (
  SELECT m.link_id FROM shorten_url.metadata m
  JOIN shorten_url.links l ON l.id = m.link_id
  WHERE m.status = 'pending' AND m.next_attempt_at <= $2
    AND m.attempts < 3 AND l.deactivated_at IS NULL AND l.expires_at > $2
  ORDER BY m.next_attempt_at, l.created_at LIMIT 1
  FOR UPDATE OF m SKIP LOCKED
)
RETURNING link_id, attempts
`

type ClaimMetadataParams struct {
	LeaseUntil int64
	Now        int64
}

type ClaimMetadataRow struct {
	LinkID   string
	Attempts int64
}

func (q *Queries) ClaimMetadata(ctx context.Context, arg ClaimMetadataParams) (ClaimMetadataRow, error) {
	row := q.db.QueryRow(ctx, claimMetadata, arg.LeaseUntil, arg.Now)
	var i ClaimMetadataRow
	err := row.Scan(&i.LinkID, &i.Attempts)
	return i, err
}

const completeMetadata = `-- name: CompleteMetadata :exec
UPDATE shorten_url.metadata
SET title = $1, description = $2, image_url = $3, fetched_at = $4, status = 'ready'
WHERE link_id = $5 AND status = 'pending' AND attempts = $6
`

type CompleteMetadataParams struct {
	Title       string
	Description string
	ImageUrl    string
	FetchedAt   sql.NullInt64
	LinkID      string
	Attempts    int64
}

func (q *Queries) CompleteMetadata(ctx context.Context, arg CompleteMetadataParams) error {
	_, err := q.db.Exec(ctx, completeMetadata,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.FetchedAt,
		arg.LinkID,
		arg.Attempts,
	)
	return err
}

const enqueueMetadata = `-- name: EnqueueMetadata :exec
INSERT INTO shorten_url.metadata (link_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnqueueMetadata(ctx context.Context, linkID string) error {
	_, err := q.db.Exec(ctx, enqueueMetadata, linkID)
	return err
}

const expireMetadataAttempts = `-- name: ExpireMetadataAttempts :exec
UPDATE shorten_url.metadata SET status = 'failed'
WHERE status = 'pending' AND attempts >= 3 AND next_attempt_at <= $1
`

func (q *Queries) ExpireMetadataAttempts(ctx context.Context, nextAttemptAt int64) error {
	_, err := q.db.Exec(ctx, expireMetadataAttempts, nextAttemptAt)
	return err
}

const failMetadata = `-- name: FailMetadata :exec
UPDATE shorten_url.metadata
SET status = CASE WHEN attempts >= 3 THEN 'failed' ELSE 'pending' END,
    next_attempt_at = $1
WHERE link_id = $2 AND status = 'pending' AND attempts = $3
`

type FailMetadataParams struct {
	NextAttemptAt int64
	LinkID        string
	Attempts      int64
}

func (q *Queries) FailMetadata(ctx context.Context, arg FailMetadataParams) error {
	_, err := q.db.Exec(ctx, failMetadata, arg.NextAttemptAt, arg.LinkID, arg.Attempts)
	return err
}

const getMetadata = `-- name: GetMetadata :one
SELECT title, description, image_url, fetched_at
FROM shorten_url.metadata WHERE link_id = $1 AND status = 'ready'
`

type GetMetadataRow struct {
	Title       string
	Description string
	ImageUrl    string
	FetchedAt   sql.NullInt64
}

func (q *Queries) GetMetadata(ctx context.Context, linkID string) (GetMetadataRow, error) {
	row := q.db.QueryRow(ctx, getMetadata, linkID)
	var i GetMetadataRow
	err := row.Scan(
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.FetchedAt,
	)
	return i, err
}

const getMetadataJobURL = `-- name: GetMetadataJobURL :one
SELECT long_url FROM shorten_url.links WHERE id = $1
`

func (q *Queries) GetMetadataJobURL(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getMetadataJobURL, id)
	var long_url string
	err := row.Scan(&long_url)
	return long_url, err
}
