// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"database/sql"
)

type ShortenUrlLink struct {
	ID             string
	UserID         string
	LongUrl        string
	ShortCode      string
	IdempotencyKey string
	CreatedAt      int64
	ExpiresAt      int64
	DeactivatedAt  sql.NullInt64
}

type ShortenUrlMetadatum struct {
	LinkID        string
	Title         string
	Description   string
	ImageUrl      string
	FetchedAt     sql.NullInt64
	Status        string
	Attempts      int64
	NextAttemptAt int64
}
