// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
)

// CreateShortenURLRequest defines model for CreateShortenURLRequest.
type CreateShortenURLRequest struct {
	LongUrl string `json:"long_url"`
}

// CreateShortenURLResponse defines model for CreateShortenURLResponse.
type CreateShortenURLResponse struct {
	ExpiresAt time.Time `json:"expires_at"`
	LongUrl   string    `json:"long_url"`
	ShortUrl  string    `json:"short_url"`
}

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	ErrorSlug  string `json:"error_slug"`
	Message    string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details []ErrorDetails `json:"details"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Stable error slug
	Slug string `json:"slug"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// CreateShortenURLParams defines parameters for CreateShortenURL.
type CreateShortenURLParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateShortenURLJSONRequestBody defines body for CreateShortenURL for application/json ContentType.
type CreateShortenURLJSONRequestBody = CreateShortenURLRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /r/{short_code})
	ResolveShortenURL(ctx *echo.Context, shortCode string) error

	// (POST /shorten-url)
	CreateShortenURL(ctx *echo.Context, params CreateShortenURLParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ResolveShortenURL converts echo context to params.
func (w *ServerInterfaceWrapper) ResolveShortenURL(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "short_code" -------------
	var shortCode string

	err = runtime.BindStyledParameterWithOptions("simple", "short_code", ctx.Param("short_code"), &shortCode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter short_code: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResolveShortenURL(ctx, shortCode)
	return err
}

// CreateShortenURL converts echo context to params.
func (w *ServerInterfaceWrapper) CreateShortenURL(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateShortenURLParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Idempotency-Key, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Idempotency-Key: %s", err))
		}

		params.IdempotencyKey = IdempotencyKey
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Idempotency-Key is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateShortenURL(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/shorten-url", wrapper.CreateShortenURL, options.OperationMiddlewares["createShortenURL"]...)
	router.GET(options.BaseURL+"/r/:short_code", wrapper.ResolveShortenURL, options.OperationMiddlewares["resolveShortenURL"]...)

}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type ResolveShortenURLRequestObject struct {
	ShortCode string `json:"short_code"`
}

type ResolveShortenURLResponseObject interface {
	VisitResolveShortenURLResponse(w http.ResponseWriter) error
}

type ResolveShortenURL307ResponseHeaders struct {
	Location string
}

type ResolveShortenURL307Response struct {
	Headers ResolveShortenURL307ResponseHeaders
}

func (response ResolveShortenURL307Response) VisitResolveShortenURLResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(307)
	return nil
}

type ResolveShortenURL404JSONResponse struct{ NotFoundJSONResponse }

func (response ResolveShortenURL404JSONResponse) VisitResolveShortenURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ResolveShortenURL500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ResolveShortenURL500JSONResponse) VisitResolveShortenURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShortenURLRequestObject struct {
	Params CreateShortenURLParams
	Body   *CreateShortenURLJSONRequestBody
}

type CreateShortenURLResponseObject interface {
	VisitCreateShortenURLResponse(w http.ResponseWriter) error
}

type CreateShortenURL201JSONResponse CreateShortenURLResponse

func (response CreateShortenURL201JSONResponse) VisitCreateShortenURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShortenURL400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateShortenURL400JSONResponse) VisitCreateShortenURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShortenURL409JSONResponse struct{ ConflictJSONResponse }

func (response CreateShortenURL409JSONResponse) VisitCreateShortenURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShortenURL500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateShortenURL500JSONResponse) VisitCreateShortenURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /r/{short_code})
	ResolveShortenURL(ctx context.Context, request ResolveShortenURLRequestObject) (ResolveShortenURLResponseObject, error)

	// (POST /shorten-url)
	CreateShortenURL(ctx context.Context, request CreateShortenURLRequestObject) (CreateShortenURLResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ResolveShortenURL operation middleware
func (sh *strictHandler) ResolveShortenURL(ctx *echo.Context, shortCode string) error {
	var request ResolveShortenURLRequestObject

	request.ShortCode = shortCode

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ResolveShortenURL(ctx.Request().Context(), request.(ResolveShortenURLRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResolveShortenURL")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ResolveShortenURLResponseObject); ok {
		return validResponse.VisitResolveShortenURLResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateShortenURL operation middleware
func (sh *strictHandler) CreateShortenURL(ctx *echo.Context, params CreateShortenURLParams) error {
	var request CreateShortenURLRequestObject

	request.Params = params

	var body CreateShortenURLJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateShortenURL(ctx.Request().Context(), request.(CreateShortenURLRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateShortenURL")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateShortenURLResponseObject); ok {
		return validResponse.VisitCreateShortenURLResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
