// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: service.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QRCodeService_GenerateQRCode_FullMethodName = "/htqrcode.qrcode.v1.QRCodeService/GenerateQRCode"
)

// QRCodeServiceClient is the client API for QRCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QRCodeServiceClient interface {
	GenerateQRCode(ctx context.Context, in *GenerateQRCodeRequest, opts ...grpc.CallOption) (*GenerateQRCodeResponse, error)
}

type qRCodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQRCodeServiceClient(cc grpc.ClientConnInterface) QRCodeServiceClient {
	return &qRCodeServiceClient{cc}
}

func (c *qRCodeServiceClient) GenerateQRCode(ctx context.Context, in *GenerateQRCodeRequest, opts ...grpc.CallOption) (*GenerateQRCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateQRCodeResponse)
	err := c.cc.Invoke(ctx, QRCodeService_GenerateQRCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QRCodeServiceServer is the server API for QRCodeService service.
// All implementations must embed UnimplementedQRCodeServiceServer
// for forward compatibility.
type QRCodeServiceServer interface {
	GenerateQRCode(context.Context, *GenerateQRCodeRequest) (*GenerateQRCodeResponse, error)
	mustEmbedUnimplementedQRCodeServiceServer()
}

// UnimplementedQRCodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQRCodeServiceServer struct{}

func (UnimplementedQRCodeServiceServer) GenerateQRCode(context.Context, *GenerateQRCodeRequest) (*GenerateQRCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateQRCode not implemented")
}
func (UnimplementedQRCodeServiceServer) mustEmbedUnimplementedQRCodeServiceServer() {}
func (UnimplementedQRCodeServiceServer) testEmbeddedByValue()                       {}

// UnsafeQRCodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QRCodeServiceServer will
// result in compilation errors.
type UnsafeQRCodeServiceServer interface {
	mustEmbedUnimplementedQRCodeServiceServer()
}

func RegisterQRCodeServiceServer(s grpc.ServiceRegistrar, srv QRCodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedQRCodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QRCodeService_ServiceDesc, srv)
}

func _QRCodeService_GenerateQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQRCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).GenerateQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QRCodeService_GenerateQRCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).GenerateQRCode(ctx, req.(*GenerateQRCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QRCodeService_ServiceDesc is the grpc.ServiceDesc for QRCodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QRCodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "htqrcode.qrcode.v1.QRCodeService",
	HandlerType: (*QRCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateQRCode",
			Handler:    _QRCodeService_GenerateQRCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
