// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: service.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Fields required for each type match the REST MessageRequest contract.
// Unknown or omitted types use text.
type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	WifiName      string                 `protobuf:"bytes,2,opt,name=wifi_name,json=wifiName,proto3" json:"wifi_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Subject       string                 `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	Latitude      string                 `protobuf:"bytes,9,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     string                 `protobuf:"bytes,10,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Label         string                 `protobuf:"bytes,11,opt,name=label,proto3" json:"label,omitempty"`
	Name          string                 `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,13,opt,name=phone,proto3" json:"phone,omitempty"`
	Organization  string                 `protobuf:"bytes,14,opt,name=organization,proto3" json:"organization,omitempty"`
	Title         string                 `protobuf:"bytes,15,opt,name=title,proto3" json:"title,omitempty"`
	Address       string                 `protobuf:"bytes,16,opt,name=address,proto3" json:"address,omitempty"`
	Website       string                 `protobuf:"bytes,17,opt,name=website,proto3" json:"website,omitempty"`
	Summary       string                 `protobuf:"bytes,18,opt,name=summary,proto3" json:"summary,omitempty"`
	Location      string                 `protobuf:"bytes,19,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     string                 `protobuf:"bytes,21,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,22,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Text          string                 `protobuf:"bytes,23,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessageRequest) GetWifiName() string {
	if x != nil {
		return x.WifiName
	}
	return ""
}

func (x *MessageRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MessageRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *MessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MessageRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MessageRequest) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *MessageRequest) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *MessageRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *MessageRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *MessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MessageRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *MessageRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *MessageRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *MessageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MessageRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MessageRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *MessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Omitted width and border default to 10. Explicit border_width=0 is supported.
// Circle mode takes precedence over custom shape and halftone options.
type Options struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QrWidth         *uint32                `protobuf:"varint,1,opt,name=qr_width,json=qrWidth,proto3,oneof" json:"qr_width,omitempty"`             // 6-255
	BorderWidth     *uint32                `protobuf:"varint,2,opt,name=border_width,json=borderWidth,proto3,oneof" json:"border_width,omitempty"` // 0-1024
	IsCircleShape   bool                   `protobuf:"varint,3,opt,name=is_circle_shape,json=isCircleShape,proto3" json:"is_circle_shape,omitempty"`
	IsCustomShape   bool                   `protobuf:"varint,4,opt,name=is_custom_shape,json=isCustomShape,proto3" json:"is_custom_shape,omitempty"`
	ForegroundColor string                 `protobuf:"bytes,5,opt,name=foreground_color,json=foregroundColor,proto3" json:"foreground_color,omitempty"` // Six-digit RGB hex, optional leading hash.
	LogoImg         []byte                 `protobuf:"bytes,6,opt,name=logo_img,json=logoImg,proto3" json:"logo_img,omitempty"`                         // PNG/JPEG, at most 1 MiB and 500x500 pixels.
	HalftoneImg     []byte                 `protobuf:"bytes,7,opt,name=halftone_img,json=halftoneImg,proto3" json:"halftone_img,omitempty"`             // PNG/JPEG, at most 5 MiB and 4096x4096 pixels.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetQrWidth() uint32 {
	if x != nil && x.QrWidth != nil {
		return *x.QrWidth
	}
	return 0
}

func (x *Options) GetBorderWidth() uint32 {
	if x != nil && x.BorderWidth != nil {
		return *x.BorderWidth
	}
	return 0
}

func (x *Options) GetIsCircleShape() bool {
	if x != nil {
		return x.IsCircleShape
	}
	return false
}

func (x *Options) GetIsCustomShape() bool {
	if x != nil {
		return x.IsCustomShape
	}
	return false
}

func (x *Options) GetForegroundColor() string {
	if x != nil {
		return x.ForegroundColor
	}
	return ""
}

func (x *Options) GetLogoImg() []byte {
	if x != nil {
		return x.LogoImg
	}
	return nil
}

func (x *Options) GetHalftoneImg() []byte {
	if x != nil {
		return x.HalftoneImg
	}
	return nil
}

// Serialized requests are limited to 8 MiB; output is at most 4096x4096 pixels.
type GenerateQRCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageRequest        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Options       *Options               `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRCodeRequest) Reset() {
	*x = GenerateQRCodeRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRCodeRequest) ProtoMessage() {}

func (x *GenerateQRCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateQRCodeRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateQRCodeRequest) GetMessage() *MessageRequest {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GenerateQRCodeRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type GenerateQRCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // image/png
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRCodeResponse) Reset() {
	*x = GenerateQRCodeResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRCodeResponse) ProtoMessage() {}

func (x *GenerateQRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateQRCodeResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateQRCodeResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *GenerateQRCodeResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x12htqrcode.qrcode.v1\"\xec\x04\n" +
	"\x0eMessageRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\twifi_name\x18\x02 \x01(\tR\bwifiName\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x12\x1a\n" +
	"\blatitude\x18\t \x01(\tR\blatitude\x12\x1c\n" +
	"\tlongitude\x18\n" +
	" \x01(\tR\tlongitude\x12\x14\n" +
	"\x05label\x18\v \x01(\tR\x05label\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\r \x01(\tR\x05phone\x12\"\n" +
	"\forganization\x18\x0e \x01(\tR\forganization\x12\x14\n" +
	"\x05title\x18\x0f \x01(\tR\x05title\x12\x18\n" +
	"\aaddress\x18\x10 \x01(\tR\aaddress\x12\x18\n" +
	"\awebsite\x18\x11 \x01(\tR\awebsite\x12\x18\n" +
	"\asummary\x18\x12 \x01(\tR\asummary\x12\x1a\n" +
	"\blocation\x18\x13 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x14 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x15 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x16 \x01(\tR\aendTime\x12\x12\n" +
	"\x04text\x18\x17 \x01(\tR\x04text\"\xa8\x02\n" +
	"\aOptions\x12\x1e\n" +
	"\bqr_width\x18\x01 \x01(\rH\x00R\aqrWidth\x88\x01\x01\x12&\n" +
	"\fborder_width\x18\x02 \x01(\rH\x01R\vborderWidth\x88\x01\x01\x12&\n" +
	"\x0fis_circle_shape\x18\x03 \x01(\bR\risCircleShape\x12&\n" +
	"\x0fis_custom_shape\x18\x04 \x01(\bR\risCustomShape\x12)\n" +
	"\x10foreground_color\x18\x05 \x01(\tR\x0fforegroundColor\x12\x19\n" +
	"\blogo_img\x18\x06 \x01(\fR\alogoImg\x12!\n" +
	"\fhalftone_img\x18\a \x01(\fR\vhalftoneImgB\v\n" +
	"\t_qr_widthB\x0f\n" +
	"\r_border_width\"\x8c\x01\n" +
	"\x15GenerateQRCodeRequest\x12<\n" +
	"\amessage\x18\x01 \x01(\v2\".htqrcode.qrcode.v1.MessageRequestR\amessage\x125\n" +
	"\aoptions\x18\x02 \x01(\v2\x1b.htqrcode.qrcode.v1.OptionsR\aoptions\"Q\n" +
	"\x16GenerateQRCodeResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType2x\n" +
	"\rQRCodeService\x12g\n" +
	"\x0eGenerateQRCode\x12).htqrcode.qrcode.v1.GenerateQRCodeRequest\x1a*.htqrcode.qrcode.v1.GenerateQRCodeResponseB\"Z htqrcode/qrcode/api/grpc;grpcapib\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_proto_goTypes = []any{
	(*MessageRequest)(nil),         // 0: htqrcode.qrcode.v1.MessageRequest
	(*Options)(nil),                // 1: htqrcode.qrcode.v1.Options
	(*GenerateQRCodeRequest)(nil),  // 2: htqrcode.qrcode.v1.GenerateQRCodeRequest
	(*GenerateQRCodeResponse)(nil), // 3: htqrcode.qrcode.v1.GenerateQRCodeResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: htqrcode.qrcode.v1.GenerateQRCodeRequest.message:type_name -> htqrcode.qrcode.v1.MessageRequest
	1, // 1: htqrcode.qrcode.v1.GenerateQRCodeRequest.options:type_name -> htqrcode.qrcode.v1.Options
	2, // 2: htqrcode.qrcode.v1.QRCodeService.GenerateQRCode:input_type -> htqrcode.qrcode.v1.GenerateQRCodeRequest
	3, // 3: htqrcode.qrcode.v1.QRCodeService.GenerateQRCode:output_type -> htqrcode.qrcode.v1.GenerateQRCodeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
